apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJU2E4bGE1WGw3bjB3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBMU1Ea3hNakV5TXpGYUZ3MHpOVEExTURjeE1qRTNNekZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURVNDFrdlEvT2d0Vzhzb2QxZFA4NnhsTHhoZFlXYmtjWlpNZkdYUDRDMWM3UDdmby9pbTFnYXdRN2UKeWwrMExlSVFyNGduTkRsZDV4dWxNWUkyeUZCU3l5QmMwbURXWVhuSy85eURtTDNPOTBOTXc3L3Fmc09KSXhWUApkNWhvYmxUdmpGME9mTUw5ZEVSUGRDUVFHdlVtaEJJc2huN3ZYZjUwQVNJcWVnakRibngyT0V1VjFvbGZGNHJSCkk1c2hiV2JaaXU4cTJxNVc4VmV0a1IrYXpYVjBFVEpiWW8wSEpMM2FqWUl6emJ5YUFlenhNZ3JleTBGZnpuU08KQWxGdDd0Zmx4OXFwQlF6NEY2Lzd0dWJpYmI5UnMxT2hHNHYxR29vSGtuZ01objdsZEJpcjc1NTJURzlTYW5taQpyaFJ1ZVpqMGUvTVQwTnM4MFFkM1NTY2p2elFQQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSWlo1TnMzSW9OUzFlaW9qZWNaTUFzY2E5bGNUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRRE9NOEZKbGN6RQpOcnhSRGUvZ3Q3SGV6aUpvb1BERzREcXJaNWJBQUZXWjRIMTZGd0gzMFU5c0JhVFlFUy9jbC9lNVpHSTlnMzFxCmhjdW9RNUgyS3gzNGlYSk8yL29jUmZvelVNMHl1dkZlTGpRZUIzOSthMXp1eC8vcHA5R2dnU29YeU5GV1V0Y2wKWFo3b3pmUFhSMyt3cUwzeFJva1UyeVc5NCt4MHlHMittLy9BUklyanpOMFJSSEJKeElVTUNhVGZ2U3RFUWI2VgoxQ1VsRE1JY2k4S3ZRTUpkQ05xSmhVdU51YUpjMUc1bHpqM2RJdnRqTVZuY1pjZXJJeFd5Zzhsa1lQSE0raGpYCnYyak12dloydGVUVklpVlllNHEwM0ZQbU1DSjk4cThIanUxZFR5SmdwRlowMi9PMUFTL1lycGpWdkIxMDBqQm0KOHRVWlpBZnVpN1hUCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://891CDE6F2E81AEF9E5E862AFB0E88EB2.gr7.ap-south-1.eks.amazonaws.com
  name: arn:aws:eks:ap-south-1:869935075210:cluster/ecommerce-cluster
contexts:
- context:
    cluster: arn:aws:eks:ap-south-1:869935075210:cluster/ecommerce-cluster
    user: arn:aws:eks:ap-south-1:869935075210:cluster/ecommerce-cluster
  name: arn:aws:eks:ap-south-1:869935075210:cluster/ecommerce-cluster
current-context: arn:aws:eks:ap-south-1:869935075210:cluster/ecommerce-cluster
kind: Config
preferences: {}
users:
- name: arn:aws:eks:ap-south-1:869935075210:cluster/ecommerce-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - ap-south-1
      - eks
      - get-token
      - --cluster-name
      - ecommerce-cluster
      - --output
      - json
      command: aws
